export const categories = [
  "General Expense",
  "Home insurance",
  "Auto insurance",
  "Health insurance",
  "Water bill",
  "Garbage bill",
  "Groceries",
  "Car payment",
  "Internet",
  "Child care",
  "Clothes",
  "Furniture",
  "Home appliance",
  "Rent",
  "Gasoline",
];
